defaults: &defaults
  access_key_id: <%=ENV['AWS_ACCESS_KEY_ID']%>
  secret_access_key: <%=ENV['AWS_SECRET_KEY']%>
  acl: public-read # options: private, public-read, public-read-write, authenticated-read
  max_file_size: 5242880 # 5 megabytes

development:
  <<: *defaults
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>

test:
  <<: *defaults
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>

production:
  <<: *defaults
  bucket: <%= ENV['AWS_BUCKET_NAME'] %>
