
development:
  adapter: postgresql
  database: rm_dev
  host: localhost
  encoding: unicode
  pool: 5

test:
  adapter: postgresql
  database: rm_test
  host: localhost
  encoding: unicode
  pool: 5

production:
  adapter: postgresql
  database: rm_prod
  host: localhost
  encoding: unicode
  pool: 5