
development:
  adapter: postgresql
  database: rm_dev
  host: localhost
  encoding: unicode
  pool: 5

test:
  adapter: postgresql
  database: rm_test
  host: localhost
  encoding: unicode
  pool: 5


production:
  adapter: postgresql
  database: rm_dev
  host: localhost
  encoding: unicode
  pool: 5
  # url:  <%= ENV["DATABASE_URL"] %>
  # pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>